voteee/poll/urls.py
from django.urls import path
from poll.views import *
app_name="poll"
urlpatterns = [
    path('list',IndexView.as_view(),name='list-view'),
    path('<int:pk>/',QDetailView.as_view(),name="poll_question_detail"),
    path('<int:pk>/results',QResultsView.as_view(),name="results"),
    path('<int:question_id>/vote',vote,name="vote")
]

voteee/voteee/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('poll.urls'))
]

voteee/poll/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    text=models.CharField(max_length=1000)
    pub_date=models.DateTimeField('date published')
    def __str__(self):
        return str(self.text)
class Choice(models.Model):
    question=models.ForeignKey(Question,on_delete=models.CASCADE)
    choice=models.TextField(max_length=200)
    votes=models.IntegerField(default=0)    
    def __str__(self):
        return f"{self.question.text}-->{self.choice}"

voteee/poll/views.py
from django.shortcuts import render,get_list_or_404,get_object_or_404
from django.template import loader
from django.http import HttpResponse,Http404,HttpResponseRedirect
from poll.models import Question,Choice
from django.urls import reverse
from django.db.models import F
from django.views import generic
from django.views.generic import *
# Create your views here.
def index(request):
    template=loader.get_template("poll/index.html")
    latest_questions=Question.objects.order_by("-pub_date")[:5]
    #return HttpResponse("-".join(str(question.text) for question in top_two_question))
    context={"latest_questions_list":latest_questions}
    return HttpResponse(template.render(context,request))
def detail(request, question_id):
    #try:
        #question=Question.objects.get(pk=question_id)
    #except Question.DoesNotExist:  
        #raise Http404("question is not found,id is invalid")
    question=get_object_or_404(Question,pk=question_id)
    context={"question":question}
    return render(request,"poll/detail.html",context)
    


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "poll/results.html", {"question": question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request,"poll/detail.html", {"question": question,"error_message": "You didn't select a choice.",})
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("poll:results", args=(question.id,)))
#--------------generic views - class based view------------
class IndexView(ListView):
    template_name = "poll/index.html"
    context_object_name ="latest_questions_list"
    def get_queryset(self):
        return Question.objects.order_by("-pub_date")[:5]
class QDetailView(DetailView):
    model = Question
    template_name = "poll/detail.html"


class QResultsView(DetailView):
    model = Question
    template_name = "poll/results.html"    
    

voteee/poll/templates/poll/detail.html
<form action="{% url 'poll:vote' question.id %}" method="post">
  {% csrf_token %}
  <fieldset>
    <legend><h1>{{ question.text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
      <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
      <label for="choice{{ forloop.counter }}">{{ choice.choice }}</label><br>
    {% endfor %}
  </fieldset>
  <input type="submit" value="Vote">
</form>

voteee/poll/templates/poll/index.html
{% if latest_questions_list %}
    <ul>
    {% for question in latest_questions_list %}
        <li><a href="{%url 'poll:poll_question_detail' question.id%} ">{{ question.text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

voteee/poll/templates/poll/question.html
  <h1>{{ question.text }}</h1>
<ul>
{% for choices in question.choice_set.all %}
    <li>{{ choices.choice}}</li>
{% endfor %}
</ul>

voteee/poll/templates/poll/results.html
<h1>{{ question.text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'poll:poll_question_detail' question.id %}">Vote again?</a>